# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_collector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeds',
            old_name='source_id',
            new_name='sources',
        ),
    ]
